

#
logging:
    level:
      org:
        springframework:
          security:
            web: WARN
          hibernate: ERROR
    file:
      name: logs/application-debug.log
      max-size: 1MB
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"