name: Example Self-Hosted Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Install Dependencies
        run: |
          mkdir -p my-new-directory
          echo "Directory 'my-new-directory' created successfully!"